# Database configuration for docker contained aquarium
#
# Note: the test database uses the name set by the docker configuration for the 
# development environment.

default: &default
  adapter: <%= ENV['DB_ADAPTER'] ||= 'mysql2' %>
  encoding: utf8
  reconnect: false
  host: <%= ENV['DB_HOST'] ||= 'db' %>
  port: <%= ENV['DB_PORT'] ||= '3306' %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>

production:
  <<: *default
  pool: 100

development:
  <<: *default
  pool: 5

test:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_test
  pool: 5
  timeout: 5000
