  version: "3.7"
  services:
    e2e:
      image: cypress
      build: ./end2end
      container_name: cypress
      depends_on: 
        - frontend_test
      environment:
        - CYPRESS_BASE_URL=http://frontend_test:${FRONTEND_TEST_PORT:-3001}
      command: npx cypress run
      volumes:
        - ./end2end:/app
      networks:
        - aquarium_net
