# based on https://github.com/bahmutov/cypress-open-from-docker-compose/blob/master/e2e/cy-open.yml
# see https://github.com/bahmutov/cypress-open-from-docker-compose for setting up X11

version: "3.7"
services: 
  e2e:
    entrypoint: cypress open --project /e2e
    environment: 
      - DISPLAY=localhost:0
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - hostnet

networks:
  hostnet:
    external: true
    name: host
