# typed: strong
# This is an autogenerated file for Rails helpers.
# Please rerun bundle exec rake rails_rbi:helpers to regenerate.
module ApplicationHelper
  include Kernel
  include ActionView::Helpers
end

module CodeHelper
  include Kernel
  include ActionView::Helpers
end

module ObjectTypesHelper
  include Kernel
  include ActionView::Helpers
end

module SessionsHelper
  include Kernel
  include ActionView::Helpers
end
